from __future__ import annotations

import polars as pl

from src.shot_quality.overlap import build_overlap_table, shared_feature_set

"""
Phase 0 report generation.

Turns the loaded sources into the markdown artifact that satisfies the
roadmap's Phase 0 definition of done: row counts, a feature-overlap table, and
the sanity checks that tell you whether the joined-up feature set is credible.
"""

# Distance buckets used for the shooting-rate sanity check, in feet.
DISTANCE_BUCKET_EDGES = [0.0, 4.0, 10.0, 16.0, 22.0, 28.0]
# Defender-distance buckets mirror the NBA's own tracking buckets (0-2, 2-4,
# 4-6, 6+ feet) so the 2014-15 effect can later be compared to leaguedashptstats.
DEFENDER_BUCKET_EDGES = [0.0, 2.0, 4.0, 6.0]


def summarize_sources(sources: dict[str, pl.DataFrame]) -> pl.DataFrame:
    """
    Row counts, season coverage and overall make rate per source.
    """
    rows = []
    for name, frame in sources.items():
        seasons = sorted(frame.get_column("season").unique().drop_nulls().to_list())
        rows.append(
            {
                "source": name,
                "rows": frame.height,
                "seasons": ", ".join(str(season) for season in seasons),
                "games": frame.get_column("game_id").n_unique(),
                "make_rate": round(frame.get_column("made").mean() or 0.0, 4),
            }
        )
    return pl.DataFrame(rows)


def make_rate_by_bucket(
    data_frame: pl.DataFrame, value_column: str, edges: list[float]
) -> pl.DataFrame:
    """
    Make rate and attempt count per bucket of value_column.

    Used both for the distance sanity check (does FG% fall with distance the way
    it must?) and for the first look at the defender-distance effect.
    """
    labelled = data_frame.drop_nulls([value_column, "made"]).with_columns(
        pl.col(value_column).cut(edges, left_closed=True).alias("bucket")
    )
    return (
        labelled.group_by("bucket")
        .agg(
            [
                pl.len().alias("attempts"),
                pl.col("made").mean().round(4).alias("make_rate"),
            ]
        )
        .sort("bucket")
    )


def make_rate_by_defender_and_distance(data_frame: pl.DataFrame) -> pl.DataFrame:
    """
    Make rate by defender-distance bucket, conditioned on shot distance.

    The unconditioned version is misleading: tightly defended shots are mostly
    layups, so closer defenders look harmless until distance is held fixed.
    """
    labelled = data_frame.drop_nulls(
        ["defender_distance_ft", "shot_distance_ft", "made"]
    ).with_columns(
        [
            pl.col("defender_distance_ft")
            .cut(DEFENDER_BUCKET_EDGES, left_closed=True)
            .alias("defender_bucket"),
            pl.col("shot_distance_ft")
            .cut(DISTANCE_BUCKET_EDGES, left_closed=True)
            .alias("distance_bucket"),
        ]
    )
    return (
        labelled.group_by(["distance_bucket", "defender_bucket"])
        .agg(
            [
                pl.len().alias("attempts"),
                pl.col("made").mean().round(4).alias("make_rate"),
            ]
        )
        .sort(["distance_bucket", "defender_bucket"])
    )


def build_phase0_report(
    sources: dict[str, pl.DataFrame],
    reachability: dict[str, str],
) -> str:
    """
    Render the full Phase 0 markdown report.
    """
    sections = [
        "# Phase 0 - Data validation report",
        "",
        (
            "Generated by `main.py`. Everything below is measured from the "
            "loaded data, not copied from documentation."
        ),
        "",
        "## nba.com endpoint reachability",
        "",
        _render_table(
            pl.DataFrame(
                {
                    "host": list(reachability.keys()),
                    "result": list(reachability.values()),
                }
            )
        ),
        "",
        "## Sources loaded",
        "",
        _render_table(summarize_sources(sources)),
        "",
        "## Feature overlap",
        "",
        (
            "Values are the fraction of non-null rows for each canonical "
            "column. `shared_by_all` marks the columns every source can "
            "actually populate."
        ),
        "",
        _render_table(build_overlap_table(sources)),
        "",
        f"**Model-usable shared features:** {shared_feature_set(sources)}",
        "",
        "## Sanity check - make rate by shot distance",
        "",
    ]

    for name, frame in sources.items():
        sections += [
            f"### {name}",
            "",
            _render_table(
                make_rate_by_bucket(frame, "shot_distance_ft", DISTANCE_BUCKET_EDGES)
            ),
            "",
        ]

    defender_frames = {
        name: frame
        for name, frame in sources.items()
        if frame.get_column("defender_distance_ft").null_count() < frame.height
    }
    if defender_frames:
        sections += ["## Defender-distance effect (sources that carry it)", ""]
        for name, frame in defender_frames.items():
            sections += [
                f"### {name}",
                "",
                _render_table(
                    make_rate_by_bucket(
                        frame, "defender_distance_ft", DEFENDER_BUCKET_EDGES
                    )
                ),
                "",
                "Conditioned on shot distance:",
                "",
                _render_table(make_rate_by_defender_and_distance(frame)),
                "",
            ]

    return "\n".join(sections)


def _render_table(data_frame: pl.DataFrame) -> str:
    """
    Render a polars frame as a GitHub-flavoured markdown table.
    """
    header = "| " + " | ".join(data_frame.columns) + " |"
    divider = "| " + " | ".join("---" for _ in data_frame.columns) + " |"
    body = [
        "| " + " | ".join("" if value is None else str(value) for value in row) + " |"
        for row in data_frame.iter_rows()
    ]
    return "\n".join([header, divider, *body])
